### PR TITLE
bibliography: remove parentheses for year of publication

### PR DESCRIPTION
**Pull request by geritwagner**

### CODE REVIEW

**Comment by geritwagner** [comment]
Of course. Do you know whether this will also change in the official Word template?

**Comment by rschuetzler** [comment]
Oh, does the Word template say India? Sorry, I didn't even think to check that, I just assumed.

**Comment by rschuetzler** [comment]
I'm really sorry for the confusion. I just assumed they'd use Hyderabad in the ICIS template. If you switch it back to India, I'll merge this in

**Comment by geritwagner** [comment]
Ok, I switched it back. Perhaps, the official template will eventually be changed to Hyderabad...

**Pull request merged**
